import React from 'react';
import Container from 'react-bootstrap/Container';
import UnstyledRow from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Project from '../components/project';
import Link from '../components/link';
import Image from 'react-bootstrap/Image';
import styled from 'styled-components';

const Row = styled(UnstyledRow)`
  justify-content: center;
`;

const Paragraph = styled.p`
  margin: 1.5rem 0px;
`;

const SectionHeader = styled.h3`
  margin: 1.5rem 0px;
  font-weight: bold;
`;

const Playpen = styled.div`
  position: relative;
  overflow: hidden;
  display: flex;
  width: 100%;
  height: 22rem;
  margin: 1.5rem 0px;
`;

const LunarBaby = styled.iframe`
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
  border: none;
`;

const HeaderPlaypen = styled(Playpen)`
  height: 30rem;
`;

const HOME_URL = "camilodoa.github.io";

const Home = () => {
  return (
    <Container>
      <HeaderPlaypen>
        <LunarBaby title='Lunar baby' src={'https://'+ HOME_URL +'/ra'} name='Lunar baby' />
      </HeaderPlaypen>
        <Row>
          <Col md={'8'}>
            <Paragraph>
              Hi, I'm <b>Camilo</b>.
            </Paragraph>
            <Paragraph>
              I'm interested in web, reinforcement learning, and computational neuroscience.
              At Google, I work on the Payments Platform's frontend experiences.
              <Link src="https://payments.google.com"> Payments center</Link>,
              reusable address widgets, and signup widgets. In my spare time,
              I'm looking to contextualize machine learning concepts through art.
            </Paragraph>
            <Paragraph>
              In 2019 and 2020, I worked at the University of Oxford with
              <Link src='https://www.cs.ox.ac.uk/michael.benedikt/'> Michael Benedikt </Link>
              on the
              <Link src='http://www.cs.ox.ac.uk/projects/pdq/home.html'> PDQ </Link>
              (Proof-Driven Query planning) project. There, I developed a full-stack
              <Link src='http://pdq-webapp.cs.ox.ac.uk/react-ui'> web application </Link>
              where users can generate, save, and run
              optimal query-plans over semantically-interconnected datasources.
              You can read more about this project in our paper,
              <Link src="https://sigmodrecord.org/2022/12/31/pdq-2-0-flexible-infrastructure-for-integrating-reasoning-and-query-planning/">
                <i> PDQ 2.0: Flexible Infrastructure for Integrating Reasoning and Query Planning</i>
              </Link>,
              published in SIGMOD in 2022.
            </Paragraph>
          </Col>
        </Row>
        <Row>
          <Col md={'8'}>
            <SectionHeader>
              Selected projects
            </SectionHeader>
          </Col>
        </Row>
        <Project
          media={<Image alt='AI Melts ICE' src={'../img/ai-melts-ice.png'} fluid />}
          name='AI Melts ICE'
          link={'https://'+ HOME_URL +'/ai-melts-ice'}
          description={
            'is a web app designed to visualize\n' +
            '          historical and predicted data of county-specific ICE arrests in the US. The predictions are\n' +
            '          generated by an LSTM neural network trained on longitudinal data (2014 - 2018)\n' +
            "          from Syracuse's TRAC web API."
          }
        />
        <Project
          media={
            <Playpen>
              <LunarBaby title='Deep reinforcement learning agent' src={'https://'+ HOME_URL +'/lunarbaby'} name='Dra' />
            </Playpen>
          }
          name='Dra'
          link={'https://'+ HOME_URL +'/lunarbaby'}
          description={
            'is an art piece that explores the Sisyphean condition of a web-based\n' +
            'creature. In the canvas lives a Deep Q-Network agent that learns to approach the goal\n' +
            'at the center of the page. Whenever it reaches the goal, it teleports somewhere else.'
          }
        />
    </Container>
  );
};

export default Home;
