import React from 'react';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Image from 'react-bootstrap/Image';

export default function Projects () {
  return (
    <Container className='mt-4 full'>
      <Row className='align justify my-2 justify-content-md-center'>
        <Col lg={8} className='top bottom'>
          <Image alt='ai-melts-ice' src='../ai-melts-ice.jpg' fluid></Image>
          <h4 className='my-4'>
            <b>
              <a href="https://ai-melts-ice.ml"
              rel="noopener noreferrer" target="_blank">ai-melts-ice.ml</a>
            </b>
          </h4>
          <h5 className='my-4'>
          <b>ai-melts-ice</b> is a web app designed to source and visualize
          predictions of ICE raids in the US. They are viewable by month
          or by county and are
          generated by an LSTM neural network trained on data (2014 - 2018)
          from Syracuse's TRAC web API.
          </h5>
        </Col>
      </Row>
      <Row className='align justify my-2 justify-content-md-center'>
        <Col lg={8} className='bottom'>
          <Image alt='slepton' src='../slepton.jpg' fluid></Image>
          <h4 className='my-4'>
            <b><a href="https://slepton.tk"
           rel="noopener noreferrer" target="_blank">slepton.tk</a>
           </b>
          </h4>
          <h5 className='my-4'>
          <b>slepton</b> is an Amherst College/Pomona
          College-based music editorial that democratizes the
          documentation new rap/hip-hop releases. Every couple of weeks,
          the four featured songs rotate, and new user-submitted ones go up.
          </h5>
        </Col>
      </Row>
    </Container>
  );
}
