import React from 'react';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Image from 'react-bootstrap/Image';

export default function Trunk () {
  let general = '../general/';
  let projects = '../projects/';

  return (
    <Container className='my-2 top'>
      <Row className='align justify full my-4 justify-content-md-center top bottom'>
        <Col className='mx-4 top bottom'>
          <Image alt='me' src={general + 'me.jpg'} roundedCircle className='profile'/>
        </Col>
        <Col className='my-4'>
          <p className='my-4'>
            Hi, I'm Camilo.
          </p>
          <p className='my-4'>
            I study Computer Science at <a href="https://www.amherst.edu/" rel="noreferrer noopener" target="_blank">
            Amherst College</a>. I love working at the intersection of deep learning and web development.
          </p>
          <p className='my-4'>
            I was recently a research assistant at <a href="http://www.cs.ox.ac.uk/"
            rel="noopener noreferrer" target="_blank">Oxford</a>'s
            Department of Computer Science, working on Professor <a href="https://www.cs.ox.ac.uk/michael.benedikt/"
            rel="noopener noreferrer" target="_blank">Michael Benedikt</a>'s <a href="http://www.cs.ox.ac.uk/projects/pdq/home.html"
            rel="noopener noreferrer" target="_blank">PDQ</a> (Proof-Driven Query) planning application. There, I
             developed a full-stack <a href="http://pdq-webapp.cs.ox.ac.uk/react-ui"
             rel="noopener noreferrer" target="_blank">web application</a> that provides an interface
             for programmers to generate and save efficient query-plans for
             semantically-interconnected datasources. Next fall, I'll be starting
             as a Software Engineer at <a href="https://www.jpmorgan.com/country/US/en/jpmorgan"
             rel="noopener noreferrer" target="_blank">J.P.Morgan Chase & Co.</a>
          </p>
          <p className='my-2'>
            In 2018, I was involved in the development of <a href="https://bampfa.org/program/dimensionism-modern-art-age-einstein"
            rel="noopener noreferrer" target="_blank">Dimensionism</a>,
            an exhibition that analyzed the influence of science,
            specifically modern physics, on the artistic processes of the
            early 20th century. Jonathon Keats  wrote an <a href="https://www.forbes.com/sites/jonathonkeats/2019/02/28/dimensionism/#101870147b0f"
            rel="noopener noreferrer" target="_blank">article</a> about it for Forbes Magazine.
          </p>
        </Col>
      </Row>
      <Row className='align justify my-2 justify-content-md-center top bottom'>
        <Col lg={8} className='top'>
          <h3 className='my-2'>
            <b>
            <u>projects</u>
            </b>
          </h3>
        </Col>

        <Col lg={8} className='top'>

          <Image alt='ai-melts-ice' src={projects + 'ai-melts-ice.jpg'} fluid></Image>
          <h4 className='my-4'>
            <b>
              <a href="https://ai-melts-ice.ml"
              rel="noopener noreferrer" target="_blank">ai-melts-ice.ml</a>
            </b>
          </h4>
          <p className='my-4'>
          <b>ai-melts-ice</b> is a web app designed to source and visualize
          predictions of ICE raids in the US. They are
          generated by a neural network trained on data (2014 - 2018)
          from Syracuse's TRAC web API.
          </p>
        </Col>
      </Row>
      <Row className='align justify my-2 justify-content-md-center'>
        <Col lg={8} className='bottom'>
          <Image alt='slepton' src={projects + 'slepton.jpg'} fluid></Image>
          <h4 className='my-4'>
            <b><a href="https://slepton.tk"
           rel="noopener noreferrer" target="_blank">slepton.tk</a>
           </b>
          </h4>
          <p className='my-4'>
          <b>slepton</b> is an Amherst College/Pomona
          College-based music editorial that democratizes the
          documentation new rap/hip-hop releases. Every couple of weeks,
          the four featured songs rotate, and new user-submitted ones go up.
          </p>
        </Col>
      </Row>
    </Container>
  );
}
